[package]
name = "bevy_fps_controller"
version = "0.2.6-rc.1"
edition = "2021"
authors = ["bevy_fps_controller"]
repository = "https://github.com/qhdwight/bevy_fps_controller"
categories = ["game-engines"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Bevy plugin that adds a Source engine inspired FPS movement controller"

[dependencies]
bevy = "0.14.0-rc.3"
bevy_rapier3d = "0.27.0-rc.1"

[[example]]
name = "minimal"
path = "examples/minimal.rs"
