[package]
name = "bevy_fps_controller"
version = "0.1.2-dev"
edition = "2021"
authors = ["bevy_fps_controller"]
repository = "https://github.com/qhdwight/bevy_fps_controller"
categories = ["game-engines"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Bevy plugin that adds a Source engine inspired FPS movement controller"

[dependencies]
bevy = "0.8.0"
bevy_rapier3d = "0.16.0"

[[example]]
name = "minimal"
path = "examples/minimal.rs"